### ISSUE TITLE
sudo dht_sensor: command not found

### ISSUE THREAD

**Issue by Damaotimlin** [chetan/dht-sensor-ffi#1]
Hi @chetan ,

I'm working on a project and using dashing with RPi.

I'm want to try your gem to see if it works, but while I use
`sudo dht_sensor
`
it returns 

> command not found

Do you have any ideas of this issue ?

Please advise, thanks !

**Comment by Damaotimlin** [comment]
Hi again,

I found out if I use 
`rvmsudo dht_sensor`
It works !

However, it seems crazy hot in my room

> Temperature: 716.80 C Humidity: 870.40%

I'm using DHT11, is it set defuly to DHT22 ?

After try by ruby file and change it to DHT11, it works good!

Thanks for your great contribution!!

P.S. How to make the data update frequently ?

**Comment by chetan** [comment]
re: read frequency - IIRC it has to do with the sensor itself. It does not allow reading very frequently (say, every second). I think it has to do with how it collects the data, but not 100% sure.

**Comment by Damaotimlin** [comment]
Thanks for your reply! @chetan 
I'm now using `dashing` for update the air_temp&humidity data to browser. I it works pretty good!

Thanks!
